#include "palette.h"

/* Generated by tools/artgen/artgen.py from pal.py -- do not edit.
 *
 * Slot roles, shared by all three areas so the art reads everywhere:
 *   0 black (transparent in sprites)  1 dark gray   2 gray      3 white
 *   4 dark green   5 grass green   6 light green   7 maroon   8 brown
 *   9 tan          10 dark blue    11 red          12 light blue
 *   13 dark gold   14 yellow       15 purple
 * The cave turns the grass greens (4, 5) to stone, so grass-backed tiles sit
 * on cave floor; PvP turns them to dead grass and darkens the water (10).
 * HUD text is slot 3 and its hearts slot 11. art/coco_tileset.json's
 * palettes must match the RGB rows (tools/art_pack.py checks). */
const unsigned char coco_clut[PALETTE_ID_COUNT][2][16] = {
    /* PALETTE_ID_OVERWORLD */
    {
        { 0, 7, 56, 63, 2, 20, 51, 4, 34, 53, 8, 36, 29, 48, 54, 40 },
        { 0, 16, 32, 48, 15, 31, 47, 7, 6, 37, 12, 23, 44, 20, 36, 25 },
    },
    /* PALETTE_ID_CAVE */
    {
        { 0, 7, 56, 63, 0, 7, 51, 4, 34, 53, 8, 36, 29, 48, 54, 40 },
        { 0, 16, 32, 48, 0, 16, 47, 7, 6, 37, 12, 23, 44, 20, 36, 25 },
    },
    /* PALETTE_ID_PVP_REALM */
    {
        { 0, 7, 56, 63, 4, 6, 51, 4, 34, 53, 5, 36, 29, 48, 54, 40 },
        { 0, 16, 32, 48, 7, 4, 47, 7, 6, 37, 9, 23, 44, 20, 36, 25 },
    },
};
