#include "tiles.h"
#include "gime.h"
#include <cmoc.h>

/* Fills one 16x16 tile (8 bytes wide, 16 lines at the 160-byte stride) with a
 * single color pair. Unrolled: a memset() per line costs several times what
 * the stores it wraps do, and a redraw is 240 tiles. */
void fill_tile(unsigned char *dst, unsigned fill16)
{
    asm {
        ldx :dst
        ldd :fill16
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
        leax 160,x
        std ,x
        std 2,x
        std 4,x
        std 6,x
    }
}
