#!/usr/bin/env python3
"""Pack art/coco_tileset.json (edited in tools/tile-editor/coco.html) into
src/art_image.c, the art block FRLOGIN installs (layout in src/art.h). Fails
if the file's palettes differ from the RGB halves in src/palette.c, which are
what the game actually shows."""

from __future__ import annotations

import json
import re
import sys

BLOCK = 8192
TILE_MAP = 0x10
IMAGES = 0x80
IMAGE_BYTES = 128

# Tile ids the terrain stream uses (docs/TILE_ALLOCATION.md; 1 and 18-33 are
# dead legacy slots).
LIVE_TILES = [0] + list(range(2, 18)) + list(range(34, 52))
PLAYER_FRAMES = 8
# Image order after the player frames (src/art.h ART_FIRST_ENTITY).
ENTITIES = [
    "beaver", "snake", "goblin", "slime0", "slime1", "bat0", "bat1",
    "gorvak", "wilhelm", "wilhelm_working", "bullet", "item_gold",
    "item_sticks", "item_herb", "item_potion", "item_key",
]
PALETTES = ["overworld", "cave", "pvp"]


def fail(message: str) -> None:
    sys.exit(f"art_pack: {message}")


def rgb_palettes(palette_c: str) -> list[list[int]]:
    """The RGB (first) row of each palette id in palette.c's coco_clut."""
    rows = re.findall(r"\{\s*((?:\d+\s*,\s*){15}\d+)\s*\}", open(palette_c).read())
    return [[int(v) for v in rows[i].split(",")] for i in range(0, len(rows), 2)]


def image(rows: list[str], label: str) -> bytes:
    if len(rows) != 16 or any(len(r) != 16 for r in rows):
        fail(f"{label} is not 16x16")
    return bytes(int(r[x], 16) << 4 | int(r[x + 1], 16) for r in rows for x in range(0, 16, 2))


def main() -> None:
    tileset_path, palette_c, out = sys.argv[1:4]
    ts = json.load(open(tileset_path))
    if ts.get("projectType") != "fujirealm-coco3-tiles":
        fail(f"{tileset_path} is not a CoCo 3 tileset")
    if [ts["palettes"][n] for n in PALETTES] != rgb_palettes(palette_c):
        fail(f"{tileset_path} palettes differ from {palette_c}")

    tiles = {t["index"]: t["rows"] for t in ts["tiles"]}
    if sorted(tiles) != LIVE_TILES:
        fail("tiles must be exactly the live tile ids")
    players = {p["index"]: p["rows"] for p in ts["players"]}
    if sorted(players) != list(range(PLAYER_FRAMES)):
        fail(f"expected {PLAYER_FRAMES} player frames")
    entities = {e["name"]: e["rows"] for e in ts["entities"]}
    if sorted(entities) != sorted(ENTITIES):
        fail(f"entities must be {', '.join(ENTITIES)}")

    images = [image(tiles[t], f"tile {t}") for t in LIVE_TILES]
    images += [image(players[i], f"player {i}") for i in range(PLAYER_FRAMES)]
    images += [image(entities[n], f"entity {n}") for n in ENTITIES]
    if IMAGES + len(images) * IMAGE_BYTES > BLOCK:
        fail("images overflow the block")

    block = bytearray(BLOCK)
    block[0:4] = b"FA" + bytes([1, len(images)])
    # Dead ids draw grass (image 0) rather than read past the images.
    for i, t in enumerate(LIVE_TILES):
        block[TILE_MAP + t] = i
    for i, img in enumerate(images):
        block[IMAGES + i * IMAGE_BYTES:IMAGES + (i + 1) * IMAGE_BYTES] = img

    lines = ["/* Generated by tools/art_pack.py -- do not edit. */", "",
             f"const unsigned char art_image[{BLOCK}] = {{"]
    for i in range(0, BLOCK, 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in block[i:i + 16]) + ",")
    lines.append("};")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
