#!/usr/bin/env python3
"""Write the C header that defines the CoCo 3 client's server connection
defaults. Mirrors tools/write_server_host_default.py's job for the Atari
client, in CMOC-friendly form (a plain header instead of a MADS include)."""

from __future__ import annotations

import sys
from pathlib import Path

MAX_HOST_LEN = 32


def parse_port(value: str, name: str) -> int:
    try:
        port = int(value, 10)
    except ValueError as exc:
        raise ValueError(f"{name} must be a decimal integer") from exc
    if not 1 <= port <= 65535:
        raise ValueError(f"{name} must be between 1 and 65535")
    return port


def render_header(host: str, hybrid_port: int, login_port: int) -> str:
    try:
        host.encode("ascii")
    except UnicodeEncodeError as exc:
        raise ValueError("SERVER_HOST must be ASCII") from exc
    if not host:
        raise ValueError("SERVER_HOST must not be empty")
    if len(host) > MAX_HOST_LEN:
        raise ValueError(f"SERVER_HOST must be {MAX_HOST_LEN} bytes or less")

    return (
        "/* Generated by tools/gen_server_host_default.py -- do not edit. */\n"
        "#ifndef SERVER_HOST_DEFAULT_H\n"
        "#define SERVER_HOST_DEFAULT_H\n"
        "\n"
        f'#define SERVER_HOST_DEFAULT "{host}"\n'
        f"#define HYBRID_SERVER_PORT {hybrid_port}\n"
        f"#define LOGIN_SERVER_PORT {login_port}\n"
        "\n"
        "#endif\n"
    )


def main() -> int:
    if len(sys.argv) != 5:
        print(
            "usage: gen_server_host_default.py HOST HYBRID_PORT LOGIN_PORT OUTPUT",
            file=sys.stderr,
        )
        return 2

    host, hybrid_arg, login_arg, output_arg = sys.argv[1:]

    try:
        hybrid_port = parse_port(hybrid_arg, "HYBRID_SERVER_PORT")
        login_port = parse_port(login_arg, "LOGIN_SERVER_PORT")
        content = render_header(host, hybrid_port, login_port)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    output = Path(output_arg)
    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists() and output.read_text() == content:
        return 0
    output.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
