#!/usr/bin/env python3
"""Turn the overlay's raw image and linker map into a C array for FRLOGIN:
the struct ovl_header (ovl_api.h, big-endian words) followed by the bytes.
Fails if the overlay, variables included, runs past the region's end."""

from __future__ import annotations

import re
import sys


def symbol(map_text: str, name: str) -> int:
    match = re.search(rf"Symbol: {name} \(\S+\) = ([0-9A-F]+)", map_text)
    if not match:
        raise ValueError(f"{name} not in map")
    return int(match.group(1), 16)


def main() -> int:
    if len(sys.argv) != 5:
        print("usage: ovl_pack.py OVL.raw OVL.map REGION_END_HEX out.c", file=sys.stderr)
        return 2
    raw_path, map_path, region_end, out_path = sys.argv[1:]
    with open(raw_path, "rb") as f:
        data = f.read()
    with open(map_path, encoding="ascii") as f:
        map_text = f.read()
    sections = [(int(a, 16), int(n, 16)) for a, n in
                re.findall(r"load at ([0-9A-F]+), length ([0-9A-F]+)", map_text)]
    load = min(a for a, _ in sections)
    end = max(a + n for a, n in sections)
    if end > int(region_end, 16):
        print(f"overlay ends at ${end:04X}, past the region end ${region_end}",
              file=sys.stderr)
        return 1
    print(f"overlay ${load:04X}-${end:04X} in region ending ${region_end}")
    entry = symbol(map_text, "_ovl_entry")
    image = bytes([ord("F"), ord("O")])
    for word in (load, entry, len(data)):
        image += bytes([word >> 8, word & 0xFF])
    image += data

    lines = ["/* Generated by tools/ovl_pack.py -- do not edit. */", ""]
    lines.append(f"const unsigned ovl_image_len = {len(image)};")
    lines.append("const unsigned char ovl_image[] = {")
    for i in range(0, len(image), 12):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in image[i:i + 12]) + ",")
    lines.append("};")
    with open(out_path, "w", encoding="ascii") as f:
        f.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
