#!/usr/bin/env python3
"""The CoCo 3 art as drawn: 16x16 pictures in pal.py's one-letter legend
(terrain.py, sprites.py). Writes the tile editor's tileset and palette.c from
them, or preview sheets. Regenerating the tileset overwrites edits made in
tools/tile-editor/coco.html.

  ./artgen.py --tileset ../../art/coco_tileset.json
  ./artgen.py --palette ../../src/palette.c
  ./artgen.py --previews /tmp/art        (needs Pillow)
"""

import argparse, json, sys
import pal, terrain, sprites

T, S = terrain.T, sprites.S


def check():
    errs = []
    for name, rows in list(T.items()) + list(S.items()):
        if len(rows) != 16:
            errs.append(f"{name}: {len(rows)} rows")
        for i, r in enumerate(rows):
            if len(r) != 16:
                errs.append(f"{name} row {i}: {len(r)} pixels")
            errs += [f"{name} row {i}: bad pixel {c!r}" for c in r if c not in pal.LEGEND]
    if errs:
        sys.exit('\n'.join(errs))


def over(bg, fg):
    return [''.join(f if f != '.' else b for b, f in zip(br, fr)) for br, fr in zip(bg, fg)]


def mirror(rows):
    return [r[::-1] for r in rows]


# Creatures, NPCs and pickups in the terrain stream are their sprite on grass.
G = T['grass']
TILES = {0: T['grass'], 2: T['tree'], 3: over(G, S['herb']), 4: T['tree_damaged'],
    5: T['stump'], 6: over(G, S['bullet']), 7: T['border'], 8: over(G, S['beaver']),
    9: over(G, S['snake']), 10: T['road'], 11: T['water'], 12: T['building'],
    13: T['cave_entrance'], 14: T['grave'], 15: T['cave_floor'], 16: T['cave_wall'],
    17: T['cave_exit'], 34: over(G, S['gold']), 35: over(G, S['sticks']),
    36: over(G, S['goblin']), 37: over(G, S['villager']), 38: over(G, S['grix']),
    39: over(G, S['key']), 40: over(G, S['daniel']), 41: over(G, S['wilhelm']),
    42: over(G, S['lucian']), 43: over(G, S['nerissa']), 44: over(G, S['slime0']),
    45: over(G, S['slime1']), 46: over(G, S['bat0']), 47: over(G, S['bat1']),
    48: over(G, S['gorvak']), 49: T['deep_pump'], 50: T['pump_controls'],
    51: over(G, S['wilhelm_working'])}
# src/art.h order: front, right, left, back, each standing then stepping.
PLAYERS = [S['player_front'], S['player_front_step'], S['player_right'],
    S['player_right_step'], mirror(S['player_right']), mirror(S['player_right_step']),
    S['player_back'], S['player_back_step']]
# tools/art_pack.py ENTITIES order.
ENT = ['beaver', 'snake', 'goblin', 'slime0', 'slime1', 'bat0', 'bat1', 'gorvak',
    'wilhelm', 'wilhelm_working', 'bullet', 'item_gold', 'item_sticks', 'item_herb',
    'item_potion', 'item_key']
ITEM_SPRITE = {'item_gold': 'gold', 'item_sticks': 'sticks', 'item_herb': 'herb',
    'item_potion': 'potion', 'item_key': 'key'}
ENTS = {n: S[ITEM_SPRITE.get(n, n)] for n in ENT}


def to_hex(rows):
    return [''.join('%X' % pal.LEGEND.index(c) for c in r) for r in rows]


def write_tileset(path):
    ts = json.load(open(path))
    names = {t['index']: t['name'] for t in ts['tiles']}
    ts['palettes'] = {k: [pal.code(*c) for c in v] for k, v in pal.PALETTES.items()}
    ts['tiles'] = [{'index': i, 'name': names[i], 'rows': to_hex(TILES[i])} for i in sorted(TILES)]
    ts['players'] = [{'index': i, 'rows': to_hex(r)} for i, r in enumerate(PLAYERS)]
    ts['entities'] = [{'name': n, 'rows': to_hex(ENTS[n])} for n in ENT]
    open(path, 'w').write(json.dumps(ts, indent=1) + '\n')


PALETTE_C = '''#include "palette.h"

/* Generated by tools/artgen/artgen.py from pal.py -- do not edit.
 *
 * Slot roles, shared by all three areas so the art reads everywhere:
 *   0 black (transparent in sprites)  1 dark gray   2 gray      3 white
 *   4 dark green   5 grass green   6 light green   7 maroon   8 brown
 *   9 tan          10 dark blue    11 red          12 light blue
 *   13 dark gold   14 yellow       15 purple
 * The cave turns the grass greens (4, 5) to stone, so grass-backed tiles sit
 * on cave floor; PvP turns them to dead grass and darkens the water (10).
 * HUD text is slot 3 and its hearts slot 11. art/coco_tileset.json's
 * palettes must match the RGB rows (tools/art_pack.py checks). */
const unsigned char coco_clut[PALETTE_ID_COUNT][2][16] = {
%s};
'''


def write_palette(path):
    def row(p, f):
        return ', '.join(str(f(c)) for c in p)
    body = ''
    for name, p in (('OVERWORLD', pal.OVERWORLD), ('CAVE', pal.CAVE), ('PVP_REALM', pal.PVP)):
        body += '    /* PALETTE_ID_%s */\n    {\n        { %s },\n        { %s },\n    },\n' % (
            name, row(p, lambda c: pal.code(*c)), row(p, lambda c: pal.COMPOSITE[c]))
    open(path, 'w').write(PALETTE_C % body)


def write_previews(out):
    import os, render
    os.makedirs(out, exist_ok=True)
    frames = ['Front', 'Front step', 'Right', 'Right step', 'Left', 'Left step', 'Back', 'Back step']
    for p in pal.PALETTES:
        items = [(str(i), TILES[i]) for i in sorted(TILES)] + [('P ' + n, r) for n, r in zip(frames, PLAYERS)]
        render.sheet(items, os.path.join(out, f'tiles_{p}.png'), p, cols=12)
        render.sheet([(n, ENTS[n]) for n in ENT], os.path.join(out, f'sprites_{p}.png'), p,
                     bg=T['cave_floor'] if p == 'cave' else T['grass'], cols=8)


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--tileset')
    ap.add_argument('--palette')
    ap.add_argument('--previews')
    a = ap.parse_args()
    check()
    if a.tileset:
        write_tileset(a.tileset)
    if a.palette:
        write_palette(a.palette)
    if a.previews:
        write_previews(a.previews)
