# Opaque 16x16 terrain tiles. Legend in pal.py: . d g w G e l m b t B r c o y p
T = {}

T['grass'] = [
    "eeeeeeeeeeeeeeee",
    "eeeleeeeeeeeeeee",
    "eeeGeeeeeeeleeee",
    "eeeeeeeeeeeGeeee",
    "eeeeeeleeeeeeeee",
    "eleeeeGeeeeeeeee",
    "eGeeeeeeeeeeeele",
    "eeeeeeeeeleeeeGe",
    "eeeeeeeeeGeeeeee",
    "eeeleeeeeeeeeeee",
    "eeeGeeeeeeeeleee",
    "eeeeeeeeleeeGeee",
    "eeeeeeeeGeeeeeee",
    "eleeeeeeeeeeeeee",
    "eGeeeeeleeeeeele",
    "eeeeeeeGeeeeeeGe",
]

T['tree'] = [
    "eeeeeGGGGGGeeeee",
    "eeeGGllllleGGeee",
    "eeGllllleeeeeGee",
    "eGllleeeelleeeGe",
    "eGlleeeelllleeGe",
    "GlleeleeellleeeG",
    "GleeelleeeeeeeeG",
    "GleeeeleeeeleeeG",
    "GeeeeeeeeellleeG",
    "eGeelleeeeleeeGe",
    "eGeeelleeeeeeGGe",
    "eeGGeeeeeeeGGGee",
    "eeeeGGbbbmGGeeee",
    "eeeeeGbbbmGeeeee",
    "eeeeGGbbbmmGeeee",
    "eeeeeGGGGGGeeeee",
]

T['tree_damaged'] = [
    "eeeeeeeeeeeeeeee",
    "eeeeeGGGGGeeeeee",
    "eeeeGlllleGGeeee",
    "eeeGllleeeeeGeee",
    "eeGlleeleeeeeGee",
    "eeGleeeeeeeeeGee",
    "eeeGeeleeeeeGeee",
    "eeeeGGeeeGGGeeee",
    "eeeeeeGbmGeeeeee",
    "eeeeeeGttmeeeeee",
    "eeeeeeebtmeeeeGe",
    "eeleeeGbbmeeelee",
    "eeGeeeGbbmeeeGee",
    "eeeeeGGbbmmGeeee",
    "eeeeeeGGGGGeeeee",
    "eeeeeeeeeeeeeeee",
]

T['stump'] = [
    "eeeeeeeeeeeeeeee",
    "eeeleeeeeeeeeeee",
    "eeeGeeeeeeeeeeee",
    "eeeeeeeeeeeeleee",
    "eeeeeeeeeeeeGeee",
    "eeeeebbbbbbeeeee",
    "eeeebttttttbeeee",
    "eeeebtbbbbtbeeee",
    "eeeebttbbttbeeee",
    "eeeembttttbmeeee",
    "eeeembbbbbbmeeee",
    "eeeembmbbmbmeeee",
    "eeeembbmbbbmeeee",
    "eeeGmmbbmbbmmGee",
    "eeeeGGGGGGGGGeee",
    "eeeeeeeeeeeeeeee",
]

# World edge: dense hedge and boulders, seamless in both directions.
T['border'] = [
    "GGeGGGdgGGGeGGGe",
    "GeeeGdggdGeeeGGG",
    "eellGdgwgdGllGeG",
    "GeeeGdgggdGeeeGG",
    "GGeGGGddGGGGeGGe",
    "GGGGeeGGGeeGGGGG",
    "eGGeelleGeeGGeeG",
    "GeGeeeeeGGGGeelG",
    "GGGGGeGGdgGGeeeG",
    "GGeeGGGdggdGGGGG",
    "GelleGdgwggdGeeG",
    "GeeeGGdgggdGGelG",
    "GGGeGGGdddGGGeeG",
    "eeGGeeGGGGGeeGGG",
    "GeeGGeeGeleeGGeG",
    "GGGeGGGeGeGGGGGe",
]

T['road'] = [
    "bbbbbbbbbbbbbbbb",
    "bbbbbtbbbbbbbbbm",
    "bbmbbbbbbbbbtbbb",
    "bbbbbbbmbbbbbbbb",
    "btbbbbbbbbbbbbbb",
    "bbbbbbbbbbtbbmbb",
    "bbbmbbbbbbbbbbbb",
    "bbbbbbtbbbbbbbbb",
    "bbbbbbbbbmbbbtbb",
    "mbbbbbbbbbbbbbbb",
    "bbbtbbbbbbbbmbbb",
    "bbbbbbbmbbbbbbbb",
    "bbbbbbbbbbbbtbbb",
    "btbbbbmbbbbbbbbb",
    "bbbbbbbbbtbbbbmb",
    "bbbmbbbbbbbbbbbb",
]

T['water'] = [
    "BBBBBBBBBBBBBBBB",
    "BBBccBBBBBBBBBBB",
    "BBcBBcBBBBBBwBBB",
    "BBBBBBBBBBBBBBBB",
    "BBBBBBBBBccBBBBB",
    "BBBBBBBBcBBcBBBB",
    "BwBBBBBBBBBBBBBB",
    "BBBBBBBBBBBBBBBB",
    "BBBBBccBBBBBBBBB",
    "BBBBcBBcBBBBBBcc",
    "BBBBBBBBBBBBBcBB",
    "BBBBBBBBBBwBBBBB",
    "BccBBBBBBBBBBBBB",
    "cBBcBBBBBBBBBBBB",
    "BBBBBBBBBccBBBBB",
    "BBBBBBBBcBBcBBBB",
]

# Buildings are blocks of this tile: a timber-framed front with windows.
T['building'] = [
    "bbbbbbbbbbbbbbbb",
    "bttttttbbttttttb",
    "bttttttbbttttttb",
    "btBBBBtbbtBBBBtb",
    "btBccBtbbtBccBtb",
    "btBcBBtbbtBcBBtb",
    "btBBBBtbbtBBBBtb",
    "bttttttbbttttttb",
    "bbbbbbbbbbbbbbbb",
    "btttttttbttttttb",
    "btttttttbttttttb",
    "btttttttbttttttb",
    "btttttttbttttttb",
    "btttttttbttttttb",
    "mmmmmmmmmmmmmmmm",
    "bbbbbbbbbbbbbbbb",
]

T['cave_entrance'] = [
    "eeeeGddddddGeeee",
    "eeGddggggggddGee",
    "eGdggwggggggdGGe",
    "Gdgggdddddgggdde",
    "Gdggd......dggdG",
    "dggd........dgdG",
    "dgd..........dgd",
    "dgd..........dgd",
    "dgd..........dgd",
    "ddd..........ddd",
    "dgd..........dgd",
    "Gdd..........ddG",
    "eGdmm......mmdGe",
    "eGGbbmmmmmmbbGGe",
    "eeGGbbbbbbbbGGee",
    "eeeeGGGGGGGGeeee",
]

T['grave'] = [
    "eeeeeeeeeeeeeeee",
    "eeeeeddddddeeeee",
    "eeeedggggggdeeee",
    "eeeedgwwggggdeee",
    "eeeedggggggdGeee",
    "eeeedgdddgdgdeee",
    "eeeedggggggdGeee",
    "eeeedgddddgdGeee",
    "eeeedggggggdGeee",
    "eeeeddddddddGeee",
    "eeembbbbbbbbmeee",
    "eeembmbbbmbbmeee",
    "eeembbbbbbbbmeee",
    "eeeGmmmmmmmmGeee",
    "eeleeeeeeeeeeele",
    "eeGeeeeeeeeeeeGe",
]

# Cave floor uses the grass slots: the cave palette turns them to stone.
T['cave_floor'] = [
    "eeeeeeeeeeeeeeee",
    "eeGeeeeeeeeeleee",
    "eeeeeeeeeeeeGeee",
    "eeeeeGGeeeeeeeee",
    "eeeeeGleeeeeeeee",
    "eeeeeeeeeeeeeeGe",
    "eleeeeeeeeGeeeee",
    "eGeeeeeeeeeeeeee",
    "eeeeeeeeeeeeeeee",
    "eeeeeeeeleeeGGee",
    "eeeGeeeeGeeeGlee",
    "eeeeeeeeeeeeeeee",
    "eeeeeeeeeeeeeeee",
    "eGGeeeeleeeeeeee",
    "eGleeeeGeeeeGeee",
    "eeeeeeeeeeeeeeee",
]

T['cave_wall'] = [
    "ddgggdddddggggdd",
    "dggwggdddgggwggd",
    "dgggggddggggggdd",
    "ddgggddgggdgggdd",
    "dddddddggggddddd",
    "gggdddddgggddggg",
    "ggwggdddddddgwgg",
    "gggggddmddddgggg",
    "dgggdddddgggdggd",
    "ddddddggggwggddd",
    "dggddgggggggddgg",
    "gwgddggggggdddgw",
    "gggdddgggddddggg",
    "ddddmddddddmdddd",
    "ddgggdddgggddddd",
    "dggwggddggwggddd",
]

# The way out: stone steps rising toward daylight.
T['cave_exit'] = [
    "dddddddddddddddd",
    "dddwwwwwwwwwwddd",
    "ddwyyyyyyyyyywdd",
    "ddwyyywwwwyyywdd",
    "ddgggggggggggggd",
    "ddwwwwwwwwwwwwdd",
    "dggggggggggggggd",
    "dddddddddddddddd",
    "dgggggggggggggge",
    "dwwwwwwwwwwwwwwe",
    "dggggggggggggggd",
    "dddddddddddddddd",
    "eggggggggggggggg",
    "ewwwwwwwwwwwwwwe",
    "eddddddddddddddd",
    "eeeeeeeeeeeeeeee",
]

# The Floodworks' Deep Pump: a riveted iron tank with a water outflow.
T['deep_pump'] = [
    "eeeddddddddddeee",
    "eeddggggggggddee",
    "edggwwgggggggdde",
    "edgwgggdddggggde",
    "edggggdcccdgggde",
    "edgdgdcBBBcdgdde",
    "edggggdcccdgggde",
    "edgdggggdggggdde",
    "edggggggdgggggde",
    "eddgdgggdggdgdde",
    "eeddddddddddddee",
    "eeemdddddddmeeee",
    "eeemdcccccdmeeee",
    "eeeedBcBBcdddddd",
    "eeeedcBcBccccccc",
    "eeeeddddddcBcBcB",
]

T['pump_controls'] = [
    "eeeeeeeeeeeeeeee",
    "edddddddddddddde",
    "edggggggggggggde",
    "edgryggdgggyrgde",
    "edgrrggdggyyrgde",
    "edggggddggggggde",
    "edgdddddddddddge",
    "edgdcccccccccdge",
    "edgdcBcBBcBBcdge",
    "edgdcccccccccdge",
    "edgdddddddddddge",
    "edggggggggggggde",
    "eddmdddddddmddee",
    "eeemdeeeeeeemdee",
    "eeemdeeeeeeemdee",
    "eeeGGeeeeeeeGGee",
]
